# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.postgresql.enabled }}
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: postgres
  namespace: postgres
spec:
  monitor:
    - selector:
        application: spilo
      portName: exporter
      targetPort: 9187
      kind: PodMonitor
      description: "Postgres Exporter Port"
  network:
    serviceMesh:
      mode: {{ if .Values.ambient }}ambient{{ else }}sidecar{{ end }}
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

    {{- if kindIs "slice" .Values.postgresql.ingress -}}
      {{- range .Values.postgresql.ingress }}
      - direction: Ingress
        selector:
          cluster-name: pg-cluster
        {{ . | toYaml | nindent 8 }}
      {{- end }}
    {{- else }}
      - direction: Ingress
        selector:
          cluster-name: pg-cluster
        {{- .Values.postgresql.ingress | toYaml | nindent 8 }}
    {{- end }}

      - direction: Ingress
        selector:
          cluster-name: pg-cluster
        remoteNamespace: {{ .Release.Namespace }}
        remoteSelector:
          app.kubernetes.io/name: postgres-operator

      - direction: Egress
        selector:
          cluster-name: pg-cluster
        remoteGenerated: KubeAPI
{{- end }}
