# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Auto Update

on:
  schedule:
    - cron: 0 14 * * * # daily at 8 AM Central (CST = UTCâˆ’6)

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: write # Allows writing content to the repository.
  packages: read # Allows reading the content of the repository's packages.
  pull-requests: write # Allows creating or updating pull requests.

# Abort prior jobs in the same workflow / PR
concurrency:
  group: auto-update-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-update:
    uses: defenseunicorns/uds-common/.github/workflows/callable-auto-update.yaml@10a8fbeef50416b8c4b0b86f17f6e31f84598294 # v1.24.1
    secrets: inherit # Inherits all secrets from the parent workflow.
